export const PRODUCTS = [
  {
    id: 1,
    name: "Vestido midi Aurora",
    price: "$89.900",
    numPrice: 89900,
    tag: "Nuevo",
    image: "prenda1.png",
    category: "Vestidos",
    fabric: "100% lino europeo",
    sizes: ["XS", "S", "M", "L"],
    desc: "Vestido midi en lino lavado con caída fluida y cintura marcada. Frescura natural para el día a día.",
  },
  {
    id: 2,
    name: "Blusa de seda Elise",
    price: "$54.500",
    numPrice: 54500,
    tag: "Seda",
    image: "prenda2.png",
    category: "Blusas",
    fabric: "100% seda satinada",
    sizes: ["XS", "S", "M", "L"],
    desc: "Blusa en seda con cuello envolvente y brillo sutil. Cae sobre la piel con ligereza.",
  },
  {
    id: 3,
    name: "Abrigo largo Dune",
    price: "$139.000",
    numPrice: 139000,
    tag: "Edición",
    image: "prenda3.png",
    category: "Abrigos",
    fabric: "Lana virgen 90% · cashmere 10%",
    sizes: ["S", "M", "L"],
    desc: "Abrigo largo en lana y cachemir con forro completo y línea recta. Para una temporada larga.",
  },
  {
    id: 4,
    name: "Falda plisada Coco",
    price: "$62.000",
    numPrice: 62000,
    tag: "Plisada",
    image: "prenda4.png",
    category: "Faldas",
    fabric: "Mezcla lino · algodón",
    sizes: ["XS", "S", "M", "L"],
    desc: "Falda plisada de largo midi y movimiento amplio. Elegancia relajada en cada paso.",
  },
  {
    id: 5,
    name: "Suéter de punto Rosa",
    price: "$49.900",
    numPrice: 49900,
    tag: "Top",
    image: "prenda5.png",
    category: "Blusas",
    fabric: "Lana merino 100%",
    sizes: ["S", "M", "L", "XL"],
    desc: "Suéter de punto fino con textura suave y calidez envolvente. Un básico reinventado.",
  },
  {
    id: 6,
    name: "Pantalón sastre Vino",
    price: "$78.000",
    numPrice: 78000,
    tag: "Sastre",
    image: "prenda6.png",
    category: "Pantalones",
    fabric: "Crepé reciclado",
    sizes: ["XS", "S", "M", "L", "XL"],
    desc: "Pantalón de sastre de pierna recta y tiro alto. Estiliza y combina con todo el armario.",
  },
];
